- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Install list of packages
  yum:
    name:
      - ntp
      - docker
    state: present

- name: ntpd running
  service:
          name: ntpd
          state: started
